name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[RT]C[0-9]+'

permissions:
  contents: write

jobs:
  release:
    if: github.event.repository.is_template == false
    uses: dryvist/cc-edge-pack-template/.github/workflows/cribl-pack-release.yml@main
